version: "3"
services:
  service-a:
    ports:
      - "8080:8080"
    build:
      context: ./servico_a
    environment:
      BASE_URL: http://service-b:8081
      EXPORTER_URL: http://zipkin:9411
  service-b:
    ports:
      - "8081:8081"
    build:
      context: ./servico_b
    environment:
      WEATHER_TOKEN: 'b31e34e7d8d842b4849182050243004'
      EXPORTER_URL: http://zipkin:9411
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
#  otel-collector:
#    image: otel/opentelemetry-collector:latest
#    restart: always
#    command: [ "--config=/etc/otel-collector-config.yaml" ]
#    volumes:
#      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
#    ports:
#      - "1888:1888"   # pprof extension
#      - "8888:8888"   # Prometheus metrics exposed by the collector
#      - "8889:8889"   # Prometheus exporter metrics
#      - "13133:13133" # health_check extension
#      - "4317:4317"   # OTLP gRPC receiver
#      - "55679:55679" # zpages extension