version: "3"
services:
  service-a:
    ports:
      - "8080:8080"
    build:
      context: ./servico_a
    environment:
      BASE_URL: http://service-b:8081
      ENV: 'PROD'
      OTEL_SERVICE_NAME: service-a
      OTEL_EXPORTER_OTLP_ENDPOINT: otel:4317
    depends_on:
      - otel
  service-b:
    ports:
      - "8081:8081"
    build:
      context: ./servico_b
    environment:
      WEATHER_TOKEN: 'b31e34e7d8d842b4849182050243004'
      ENV: 'PROD'
      OTEL_SERVICE_NAME: service-b
      OTEL_EXPORTER_OTLP_ENDPOINT: otel:4317
    depends_on:
      - otel
  otel:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./.docker/otel-collector-config.yaml:/conf/otel-collector-config.yaml
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    privileged: true
