version: "3"
services:
  otel:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./.docker/otel-collector-config.yaml:/conf/otel-collector-config.yaml

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    privileged: true
