receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: zipkin:4317
    tls:
      insecure: true

  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]