version: '3'
services:
  otel:
#    image: otel/opentelemetry-collector-contrib:0.100.0
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./.docker/otel-collector-config.yaml:/conf/otel-collector-config.yaml
#    links:
#      - zipkin

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    privileged: true

  goapp:
    container_name: goapp
    build:
      context: .
    environment:
      - TITLE=Microservice Demo
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=green
      - RESPONSE_TIME=1000
      - EXTERNAL_CALL_URL=http://goapp2:8181
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-demo-request
      - OTEL_SERVICE_NAME=microservice-demo
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel:4317
#      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - otel

  goapp2:
    container_name: goapp2
    build:
      context: .
    environment:
      - TITLE=Microservice Demo 2
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=blue
      - EXTERNAL_CALL_URL=http://goapp3:8282
      - EXTERNAL_CALL_METHOD=GET
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-demo2-request
      - OTEL_SERVICE_NAME=microservice-demo2
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel:4317
#      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - HTTP_PORT=:8181
    ports:
      - "8181:8181"
    depends_on:
      - otel

  goapp3:
    container_name: goapp3
    build:
      context: .
    environment:
      - TITLE=Microservice Demo 3
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=green
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-demo3-request
      - OTEL_SERVICE_NAME=microservice-demo3
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel:4317
#      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - HTTP_PORT=:8282
    ports:
      - "8282:8282"
    depends_on:
      - otel